set_recording_mode:
  description: 'Set recording mode for the camera'
  fields:
    entity_id:
      description: 'string (required) camera to enable recording on'
      example: 'camera.outdoor'
    recording_mode:
      description: '(Optional) Valid options are: always = Always Recording, motion = Only record on motion, never = stop recording. Default value is: motion'
      example: motion
